// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rlsyyvuelmrdlldwzxgn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJsc3l5dnVlbG1yZGxsZHd6eGduIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5ODkyMDgsImV4cCI6MjA3MDU2NTIwOH0.qO3dhV6DHGwWl0H857UhOXufmB0qKXzCwcBeJOCQyjI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});